### ISSUE TITLE
[BUG] deleted packages cleanup doesn't work

### ISSUE THREAD

**Issue by Minikea** [OCSInventory-NG/OCSInventory-ocsreports#1533] opened 2023-07-06 09:29 UTC
**OCS Inventory version**
Version : 2.11.1

**Describe the bug**
When you delete a package that have been deployed, you a line with "**Unknown (deleted package)**" on the deployment history of concerned computers
![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/731225/70a83fcd-9a6d-4cb9-b450-0ea11279cb8c)
I clear this history with a SQL request : 
`DELETE DH FROM download_history DH LEFT JOIN download_available DA on DH.PKG_ID = DA.FILEID WHERE DA.FILEID IS NULL;`
The request works and the history is cleared.
The bug is that it appeared to be temporary : the next day the lines "**Unknown (deleted package)**" are back.

**To Reproduce**
1. create a deployment package
2. deploy the package on some computers
3. delete the package once it is deployed successfully 
4. purge the download_history from the ID of the package deleted
5. wait one day
6. the lines are back

**Expected behavior**
the lines stays deleted

**addendum**
I have these cron jobs:
/usr/share/ocsinventory-reports/ocsreports/crontab/cron_cve.php
/usr/share/ocsinventory-reports/ocsreports/crontab/cron_cve_computer.php

**Comment by Lea9250** [comment] 2023-10-04 15:47
Hi @Minikea,

We do have a cron script in charge of clearing the history if the package has been deleted (cron_purge_history.php). However, even when using the script, I am able to reproduce the behavior you reported. We'll investigate the issue and keep you updated.

Regards,
Léa

**Comment by Lea9250** [comment] 2023-12-11 09:35
HI @Minikea, 

There is an open PR that should fix this issue on the server repository : https://github.com/OCSInventory-NG/OCSInventory-Server/pull/445

If you are willing to test it, any feedback will be appreciated. Either way I will update this issue once this has been reviewed and hopefully merged.

Best regards,
Léa

**Comment by charleneauger** [comment] 2023-12-18 13:19
Hi @Minikea,

Since the PR mentionned by @Lea9250 has been merged, I close the issue.

Best regards,
Charlene

**Closed by charleneauger** 2023-12-18 13:19 UTC
Labels: bug, need approval
