### ISSUE TITLE
[BUG] Multi-criteria search

### ISSUE THREAD

**Issue by o71** [OCSInventory-NG/OCSInventory-ocsreports#1562] opened 2023-09-27 08:33 UTC
**OCS Inventory version**
Version : 2.12.0.

**Describe the bug**
The multi-criteria search seems to malfunction with the memory capacity.

### result with a search between 1 and 5000, displays values greater than 5000

![erreur 1](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/2280629/8b909955-11a0-4d75-a47c-cf66dba58e69)

### Some PCs are displayed with 0 even though they have memory

![erreur 2 1](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/2280629/970bd256-0d7d-41b1-8563-ae16e336a3d9)

PC ***-09 hardware details :

![erreur 2 2](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/2280629/eebdcbba-06b9-4943-8cf4-cdf12eb0fecc)

Do you know what the problem is?

Thank you very much

**Comment by Lea9250** [comment] 2023-10-05 14:52
Hi @o71,

Regarding the mismatched results with less than and greater than operators : we were able to reproduce this and will be working on it, seems like the SQL query isn't built correctly. 
About the "0" displayed for some devices : the search you created will filter on individual memory slots. If at least one of the slots is under 5000, the computer will show up in the results.

If you were interested in the total memory capacity, the same search used with the field Computer - RAM(MB) should return the correct result.

Thank you for reporting the issue,
Léa

**Comment by o71** [comment] 2023-10-09 05:48
Thanks !

**Comment by Lea9250** [comment] 2023-10-11 15:44
Hi @o71,

We took some time to look more into this and it seems like the behavior of the search when dealing with multiples values for a single device (such as memory slots) is coherent after all. The criteria are applied to all the values returned for a device, rather than on each individual value, as illustrated by your third screenshot.
We do not plan on modifying it since it could impact other searches as well and lead to future issues or confusion. 

I'll close this issue as this is the expected behavior.
I hope the workaround I provided in my previous response has been helpful in your case.

Best regards,
Léa

**Closed by Lea9250** 2023-10-11 15:44 UTC
Labels: bug, need approval
