### ISSUE TITLE
[BUG] Agent doesn't show up in all_computers list

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#796] opened 2019-07-26 08:46 UTC
**OCS Inventory version**
Version : 2.6

**Describe the bug**
We have some agents that don't show up in the all_computers list.

After some troubleshooting it appears that the cause of this problem is because these agents have no network interface that's in state "Up" according to OCSI.

However, these agents work perfectly well: They contact the server regularly and are able to download packages.

Is the test `AND n.STATUS = 'up'` in ms_all_computers.php really needed?

**Expected behavior**
All working agents should show up in the all_computers list

**Screenshots**

![image](https://user-images.githubusercontent.com/8179031/61938875-5f45b280-af92-11e9-9cca-15ad4986e2d4.png)

![image](https://user-images.githubusercontent.com/8179031/61938957-88fed980-af92-11e9-8d00-e22074aa2275.png)

![image](https://user-images.githubusercontent.com/8179031/61939013-a2a02100-af92-11e9-9879-07c192413763.png)

**Comment by charleneauger** [comment] 2019-08-23 08:14
Hi @StCyr ,

Your issue is a duplicate of #722 

Best regards,
Charlene

**Closed by charleneauger** 2019-08-23 08:14 UTC
Labels: duplicate
