### ISSUE TITLE
[BUG] Download package generates invalid archive

### ISSUE THREAD

**Issue by m-bach** [OCSInventory-NG/OCSInventory-ocsreports#1362] opened 2022-04-07 10:45 UTC
**OCS Inventory version**
Version : 2.9.2

**Describe the bug**
When downloading a package from ocsreports/index.php?function=tele_activate the resulting ZIP-File is invalid. Looking at the file I found that there is an empty line before the ZIP-Header. Removing this line makes the file usable.
Looking at the code I'm not sure where the empty line is generated.

**To Reproduce**
1. Go to 'Deployment -> Activate'
2. Click on 'Download arrow' (in Actions column) on any package
3. Save the file
4. Try to open it with any archive tool

**Expected behavior**
Generated zip can be opened.

**Screenshots**
![Screenshot_2022-04-07_12-43-33](https://user-images.githubusercontent.com/88787401/162182086-b36024b3-9c96-4343-9293-342caf94ca2e.png)
![Screenshot_2022-04-07_12-44-11](https://user-images.githubusercontent.com/88787401/162182083-04c6099a-a76e-4b63-b523-e3060fe75cdc.png)

**Comment by Lea9250** [comment] 2022-12-22 13:36
Hi @m-bach,

If possible, could you upgrade to the latest version ? I was not able to reproduce this issue in 2.11.1.

Regards,
Léa

**Comment by charleneauger** [comment] 2023-03-24 08:10
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene

**Closed by charleneauger** 2023-03-24 08:10 UTC
Labels: bug, need approval
