### ISSUE TITLE
[BUG] LDAP+SSO doesn't work

### ISSUE THREAD

**Issue by timurmerezhnikov** [OCSInventory-NG/OCSInventory-ocsreports#1570] opened 2023-10-11 16:56 UTC
OCS Inventory Version : 2.12.1

Active Directory 2012

Hello,
I have installed OCS Inventory NG server, and try to setup LDAP with SSO on it, but it doen't work.

On my OCS server I setup ldap and everything works fine. Then I get my Apache2 server is able to authenticate users with mod_auth_gssapi (AD backend). Then i set this option in /usr/share/ocsinventory-reports/ocsreports/var.php:

define('AUTH_TYPE', 4);

And then I restart my Apache2 webserver. I expected that my users can login to the server using SSO.

But I get blank page instead of it..

![изображение](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/147647204/583f9042-abf6-41b8-9963-8230d5f5d308)

**Comment by Lea9250** [comment] 2023-12-04 16:15
Hi @timurmerezhnikov,

Is there any error/warning in your apache logs when logging in ?

Regards,
Léa

**Comment by matt6697** [comment] 2023-12-08 13:05
Hi,

We are facing the same issue with 2.12.0 : 
- Kerberos authentication is configured in Apache `default_ssl.conf` and authenticated user is wisible in apache access.log => Apache SSO configuration works well
- After kerberos SSO, the same blank page is visible when configuring  'AUTH_TYPE'=4 in `var.php`

**Comment by matt6697** [comment] 2023-12-08 16:12
Apache access log showing **user1@DOMAIN** as the authenticated user:
```
10.X.Y.Z - user1 [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/ HTTP/1.1" 200 7765 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.X.Y.Z - user1@DOMAIN [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/libraries/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 20257 "https://srv-ocsng.domain/ocsreports/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.X.Y.Z - user1@DOMAIN [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/libraries/bootstrap/css/bootstrap-theme.min.css HTTP/1.1" 200 3229 "https://srv-ocsng.domain/ocsreports/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.X.Y.Z - user1@DOMAIN [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/libraries/datatable/media/css/dataTables.bootstrap.css HTTP/1.1" 200 1754 "https://srv-ocsng.domain/ocsreports/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.X.Y.Z - user1@DOMAIN [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/css/ocsreports.css HTTP/1.1" 200 3202 "https://srv-ocsng.domain/ocsreports/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.X.Y.Z - user1@DOMAIN [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/css/bootstrap-formhelpers.css HTTP/1.1" 200 5408 "https://srv-ocsng.domain/ocsreports/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.X.Y.Z - user1@DOMAIN [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/libraries/select2/css/select2.min.css HTTP/1.1" 200 7831 "https://srv-ocsng.domain/ocsreports/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
10.X.Y.Z - user1@DOMAIN [08/Dec/2023:12:37:41 +0100] "GET /ocsreports/css/dataTables-custom.css HTTP/1.1" 200 7056 "https://srv-ocsng.domain/ocsreports/" "Mozilla/5
```

Apache error log:
```
[Fri Dec 08 12:19:00.468099 2023] [:error] [pid 8397] [client 10.X.Y.Z:50071] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/backend/identity/identity.php on line 49
[Fri Dec 08 12:19:00.497765 2023] [:error] [pid 8397] [client 10.X.Y.Z:50071] PHP Warning:  file_get_contents(/usr/share/ocsinventory-reports/ocsreports/config/profiles/.xml): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 377
[Fri Dec 08 12:19:00.497805 2023] [:error] [pid 8397] [client 10.X.Y.Z:50071] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 81
[Fri Dec 08 12:19:00.497809 2023] [:error] [pid 8397] [client 10.X.Y.Z:50071] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 87
[Fri Dec 08 12:19:00.497814 2023] [:error] [pid 8397] [client 10.X.Y.Z:50071] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 93
[Fri Dec 08 12:19:00.497818 2023] [:error] [pid 8397] [client 10.X.Y.Z:50071] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 97
[Fri Dec 08 12:19:00.498779 2023] [:error] [pid 8397] [client 10.X.Y.Z:50071] PHP Warning:  array_search() expects parameter 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 237
[Fri Dec 08 12:21:31.599313 2023] [:error] [pid 8312] [client 10.X.Y.Z:50209] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/backend/identity/identity.php on line 49
[Fri Dec 08 12:21:31.600737 2023] [:error] [pid 8312] [client 10.X.Y.Z:50209] PHP Warning:  array_search() expects parameter 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 237
[Fri Dec 08 12:21:32.988901 2023] [core:info] [pid 8312] [client 10.X.Y.Z:50209] AH00128: File does not exist: /usr/share/ocsinventory-reports/ocsreports/libraries/bootstrap/css/bootstrap.min.css.map
[Fri Dec 08 12:21:33.006807 2023] [core:info] [pid 8313] [client 10.X.Y.Z:50213] AH00128: File does not exist: /usr/share/ocsinventory-reports/ocsreports/libraries/bootstrap/css/bootstrap-theme.min.css.map
[Fri Dec 08 12:36:55.857123 2023] [:error] [pid 8313] [client 10.X.Y.Z:51186] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/backend/identity/identity.php on line 49
[Fri Dec 08 12:36:55.858588 2023] [:error] [pid 8313] [client 10.X.Y.Z:51186] PHP Warning:  array_search() expects parameter 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 237
[Fri Dec 08 12:36:57.142148 2023] [core:info] [pid 8397] [client 10.X.Y.Z:51194] AH00128: File does not exist: /usr/share/ocsinventory-reports/ocsreports/libraries/bootstrap/css/bootstrap-theme.min.css.map
[Fri Dec 08 12:36:57.156293 2023] [core:info] [pid 8417] [client 10.X.Y.Z:51188] AH00128: File does not exist: /usr/share/ocsinventory-reports/ocsreports/libraries/bootstrap/css/bootstrap.min.css.map
[Fri Dec 08 12:37:56.963534 2023] [:error] [pid 8312] [client 10.X.Y.Z:51247] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/backend/identity/identity.php on line 49, referer: https://srv-ocsng.domain/ocsreports/
[Fri Dec 08 12:37:56.993141 2023] [:error] [pid 8312] [client 10.X.Y.Z:51247] PHP Warning:  file_get_contents(/usr/share/ocsinventory-reports/ocsreports/config/profiles/.xml): failed to open stream: No such file or directory in /usr/share/ocsinventory-reports/ocsreports/require/header.php on line 377, referer: https://srv-ocsng.domain/ocsreports/
[Fri Dec 08 12:37:56.993175 2023] [:error] [pid 8312] [client 10.X.Y.Z:51247] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 81, referer: https://srv-ocsng.domain/ocsreports/
[Fri Dec 08 12:37:56.993180 2023] [:error] [pid 8312] [client 10.X.Y.Z:51247] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 87, referer: https://srv-ocsng.domain/ocsreports/
[Fri Dec 08 12:37:56.993184 2023] [:error] [pid 8312] [client 10.X.Y.Z:51247] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 93, referer: https://srv-ocsng.domain/ocsreports/
[Fri Dec 08 12:37:56.993188 2023] [:error] [pid 8312] [client 10.X.Y.Z:51247] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLProfileSerializer.php on line 97, referer: https://srv-ocsng.domain/ocsreports/
[Fri Dec 08 12:37:56.994166 2023] [:error] [pid 8312] [client 10.X.Y.Z:51247] PHP Warning:  array_search() expects parameter 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/html_header.php on line 237, referer: https://srv-ocsng.domain/ocsreports/
```

**Comment by matt6697** [comment] 2023-12-08 17:02
Might the issue be related with **bontiv** last comment in https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1105 ?

![image](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/assets/32440697/26b47bb6-d2c8-4297-bcbf-8c542b66f952)

**Comment by timurmerezhnikov** [comment] 2023-12-09 09:10
> Hi @timurmerezhnikov,
> 
> Is there any error/warning in your apache logs when logging in ?
> 
> Regards, Léa

Hi Léa,
Thanks for your respond.
Apache logs looks like in @matt6697 comment.

Anyway, does Kerberos SSO work correctly in the OCS Inventory Version : 2.12 server? or is it a bug? 

And is there a detailed setup Kerberos SSO instruction somewhere?

Regards,
Timur

**Comment by gillesdubois** [comment] 2023-12-13 10:32
Hello,

I recently setup Kerberos authentication with a few clean installation of OCS in the last weeks / months.
All of them seems to work properly.

CAS auth would be more recommended and OpenIDConnect when available (currently in the roadmap).

Debugging kerberos auth is a complex matter as it really depend on a lot of different variables in your environement / authentication provider.

We don't directly provide Kerberos documentation as its a bit complex a provide a generic documentation.
For exemple, generating a keytab or setting SPN / configuration client will vary depending on product usage and authentication server (ActiveDirectory / Samba / etc...)

Just a few questions that could help you find the issue root cause : 
- Are you able to kinit the generated keytab ? 
- Is so are can you perform a klist ? Is the service URL present in the Klist output ? 
- Which apache module are you using ? NTLM / GSSAPI / etc...
- What is the apache configuration setup ? 
- Did you try to setup apache in debug4 level ? What is passing through the output ?
- Did you already setup kerberos application that use apache ? Are the configuration on the same level ?

Regards,
Gilles DUBOIS.

**Comment by matt6697** [comment] 2023-12-13 13:42
Hi Gilles,

Kerberos authentication works like a charm in Apache2 (libapache2-mod-auth-kerb) and the REMOTE_USER is clearly visible in phpinfo() whan adding a `phpinfo.php` page in the `ocsreports` directory.

After further investigations, the issue is related with :
 - `backend/require/auth.manager.php` relying on `backend/AUTH/methode/always_ok.php` for authentication
 - `backend/AUTH/methode/always_ok.php` setting only `$login_successful = "OK";` but not saving user info gathered from LDAP server in `$_SESSION['OCS']['details']` as it is done in `backend/AUTH/methode/ldap.php` for LDAP authentication.

The `backend/identity/methode/ldap.php` is then used in the **identity** phase but returns `false` as `$_SESSION['OCS']['cnx_origine'] != "LDAP"` (`$_SESSION['OCS']['cnx_origine']  = "SSO"` when configuring `define('AUTH_TYPE', 4);`) Nevertheless, as the ` $_SESSION['OCS']['details']['givenname']`, `$_SESSION['OCS']['details']['sn']`... are not populated by `backend/AUTH/methode/always_ok.php` , changing the `if($_SESSION['OCS']['cnx_origine'] != "LDAP")` test might not be enough to fix the issue.

Changing the `verif_pw_ldap($login, $pw)` function of `backend/AUTH/methode/ldap.php` and changing auth manager to use `backend/AUTH/methode/ldap.php` when `define('AUTH_TYPE', 4);` fixes the issue:

**Change in `backend/AUTH/methode/ldap.php`**
```
function verif_pw_ldap($login, $pw) {
    $info = search_on_loginnt($login);
    if ($info["nbResultats"] != 1) {
        // login doesn't exist
        return ("BAD LOGIN OR PASSWORD");
    }

    $affich_method = get_affiche_methode();
    if($affich_method == 'SSO') {
        return (isset($info[0]["dn"]) ? "OK" : "BAD LOGIN OR PASSWORD");
    } else {
        return (ldap_test_pw($info[0]["dn"], $pw) ? "OK" : "BAD LOGIN OR PASSWORD");
    }
}
```

**Change in `backend/require/auth.manager.php` to use `backend/AUTH/methode/ldap.php` when `AUTH_TYPE == 4`**
```
function get_list_methode($identity = false){
    switch (AUTH_TYPE) {
        case 1:
            return array(
                0 => "local.php"
            );

        case 2:
            return array(
                0 => "local.php",
                1 => "ldap.php"
            );

        case 3:
            return array(
                0 => "ldap.php"
            );

        case 4:
            return array(
                0 => "ldap.php"
            );
            break;
         [...]
}
```

Fix is working bith with AUTH_TYPE == 2` && AUTH_TYPE == 4`

I'll push a PR with this fix.

**Comment by matt6697** [comment] 2023-12-13 13:53
PR https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1579 created

**Comment by Lea9250** [comment] 2023-12-18 13:52
Hi @timurmerezhnikov, 

#1579 fixes the issue and has been successfully merged into master. Thank you for bringing this to our attention. 
I am closing this, but feel free to reopen it if any further issues arise.

Best regards,
Léa

**Closed by Lea9250** 2023-12-18 13:52 UTC
Labels: bug, need approval

**Comment by timurmerezhnikov** [comment] 2023-12-26 02:37
Hi @Lea9250, @matt6697
Thank you so much!
