### ISSUE TITLE
[BUG] "All computers" list is empty

### ISSUE THREAD

**Issue by AHeinlein** [OCSInventory-NG/OCSInventory-ocsreports#1119] opened 2021-02-09 07:01 UTC
**OCS Inventory version**
Version :  2.8.1

**Describe the bug**
Since upgrading the server to 2.8.1, the list "All computers" is empty, both "active computers" and "archived computers". If I go to the dashboard and click on the number of inventoried computers, I get a list and can see that machines are actually being inventoried.

**To Reproduce**
1. Login to OCS Inventory
2. Click "All computers"
3. See empty list

**Expected behavior**
See list of all computers

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/22483295/107327157-f27b0600-6aac-11eb-81f9-cb42a66b58e4.png)

**Log file (optional)**
Apache / PHP / System log if needed

**Comment by gillesdubois** [comment] 2021-02-09 07:14
Hi @AHeinlein 

Can you check if you are missing the 'archive' column inside the hardware table ?
Most of the time when these kind of behavior appear, it mean that this columns hasn't been added properly during update.

Regards,
Gilles.

**Comment by AHeinlein** [comment] 2021-02-09 08:03
There is an empty table 'archive' in the database. In the 'hardware' table, there is only a column 'arch', but no '
archive'.

**Comment by gillesdubois** [comment] 2021-02-09 08:09
Ok seems like a SQL statement didn't executed properly.

Try : ```UNLOCK TABLES;
ALTER TABLE `archive` ADD UNIQUE (`HARDWARE_ID`);
ALTER TABLE `archive` ADD FOREIGN KEY (`HARDWARE_ID`) REFERENCES `hardware`(`ID`);

ALTER TABLE `hardware` ADD COLUMN `ARCHIVE` INT DEFAULT NULL;```

**Comment by AHeinlein** [comment] 2021-02-09 08:24
The second statement returns

ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by AHeinlein** [comment] 2021-02-09 08:53
The solution is here: https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/

The database was obviously created using MySQL 5.6 or earlier, all tables in the database were using COMPACT row format. I changed the row format of the hardware table to DYNAMIC, then the above statement succeeded. After that, I can see a list of all computers.

Several questions:
- That error must have been raised during the database migration when upgrading OCSInventory, but it obviously did not get caught. You might want to look into that. 
- Could you add a check with the next update that checks the row format of the tables and if necessary changes it.
- Is it possible to run the database upgrade again? I guess there might be more missing columns.

**Comment by mattoussaint** [comment] 2021-02-16 20:03
Hi, same issue but "archive" row from "hardware" table is here

**Comment by xElmerp** [comment] 2021-03-25 12:58
> Hola @AHeinlein
> 
> ¿Puede comprobar si le falta la columna 'archivo' dentro de la tabla de hardware?
> La mayoría de las veces, cuando aparecen este tipo de comportamiento, significa que estas columnas no se han agregado correctamente durante la actualización.
> 
> Saludos,
> Gilles.

how can i verify that? can you guide me please

**Comment by charleneauger** [comment] 2021-06-02 12:35
Hi,

This issue is a duplicate of #1063 

Best regards,
Charlene

**Closed by charleneauger** 2021-06-02 12:35 UTC
Labels: bug, need approval
