### ISSUE TITLE
ERROR: MySql connection problem 1045

### ISSUE THREAD

**Issue by nohnaimer** [OCSInventory-NG/OCSInventory-ocsreports#164] opened 2016-11-16 13:37 UTC
Hello,
After install and first login I get this error:
ERROR: MySql connection problem 1045
Access denied for user 'root'@'localhost' (using password: YES)
ERROR: MySql connection problem 1045
Access denied for user 'root'@'localhost' (using password: YES)

And so with anyone user. Database create and data set into database. What I am doing wrong?
OCS Inventory 2.2.1 on Github. Server Oracle Linux 7.2 with httpd 2.4.6 php 7 and Percona-server 5.7.

Thank you!

**Comment by gillesdubois** [comment] 2016-11-16 16:21
Hi,

You should check your dbconfig.inc.php file located in /usr/share/ocsinventory-reports/ocsreports ( by default )
Your database user & pass may be wrong in that file.

Regards,
Gilles Dubois.

**Comment by nohnaimer** [comment] 2016-11-16 16:51
Hi,
Thank for reply. I check config in /usr/share/ocsinventory-report/ocsreports/dbconfig.inc.php and z-ocsinventory-server.conf same data to connect to local percona-server.

In console on server I successfully log in and get access to the database. And when the server installation as a user database is created and the tables inside were created. Are there any ideas?

**Comment by nohnaimer** [comment] 2016-11-16 20:35
It may be a problem in versions of a person? 5.7 version is suitable?

**Comment by nohnaimer** [comment] 2016-11-23 13:30
The problem in the version of the mysql. With version 5.7 does not work. With 5.6- okay

**Comment by nohnaimer** [comment] 2016-11-23 13:43
If i use password ocs for connect to mysql - then all is well
If I change any other password, I receive an error

**Comment by gillesdubois** [comment] 2016-11-29 14:34
hi,

mysql 5.7 is suitable for ocsinventory

When you modify your database connection you need to update your apache config file and your dbconfig.inc.php

could you post your apache2 error log ?

Regards,
Gilles Dubois.

**Comment by nohnaimer** [comment] 2016-12-12 05:47
Sorry, there was a lot of work. Here's what you asked for:
Change password in these two files:

/etc/httpd/conf.d/z-ocsinventory-server.conf
```
# Master Database settings
  # Replace mysql-srv.inside.mts.by by hostname or ip of MySQL server for WRITE
  PerlSetEnv OCS_DB_HOST localhost
  # Replace 3306 by port where running MySQL server, generally 3306
  PerlSetEnv OCS_DB_PORT 3306
  # Name of database
  PerlSetEnv OCS_DB_NAME ocsweb
  PerlSetEnv OCS_DB_LOCAL ocsweb
  # User allowed to connect to database
  PerlSetEnv OCS_DB_USER ocs
  # Password for user
  PerlSetVar OCS_DB_PWD ocs
```
/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php
```
<?php
define("DB_NAME", "ocsweb");
define("SERVER_READ","localhost");
define("SERVER_WRITE","localhost");
define("COMPTE_BASE","ocs");
define("PSWD_BASE","ocs");
?>
```

Apache log error is empty. In access only:
```
::1 - - [12/Dec/2016:08:44:31 +0300] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 () PHP/7.0.13 mod_perl/2.0.9dev Perl/v5.16.3 (internal dummy connection)"
::1 - - [12/Dec/2016:08:44:32 +0300] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 () PHP/7.0.13 mod_perl/2.0.9dev Perl/v5.16.3 (internal dummy connection)"
```
![2016-12-12 8 45 58](https://cloud.githubusercontent.com/assets/8865830/21089248/6fca1f70-c047-11e6-8e95-a7c5ddf2a653.png)

If the password ocs - it all works. If any other - take error!

**Comment by mtbadi39** [comment] 2016-12-12 13:40
maybe you need to restart Apache each time after you modifying these files !

**Comment by nohnaimer** [comment] 2016-12-12 13:44
> maybe you need to restart Apache each time after you modifying these files !
I restart httpd after change files every time!

**Comment by mtbadi39** [comment] 2016-12-12 14:22
Then you need to GRANT ALL PRIVILEGES on OCS database TO those users :
```SQL 
grant all privileges on ocsweb.* to myuser@'%' identified by 'mypasswd';
grant all privileges on ocsweb.* to myuser@localhost identified by 'mypasswd';
```

**Comment by nohnaimer** [comment] 2016-12-12 14:41
Why need privileges for remote user:
`grant all privileges on ocsweb.* to myuser@'%' identified by 'mypasswd';`
If all located on the same server?
Privileges for my user:
![2016-12-12 17 39 55](https://cloud.githubusercontent.com/assets/8865830/21103124/2ad190a6-c092-11e6-8393-726b8b1b7342.png)

**Comment by gillesdubois** [comment] 2016-12-23 10:04
Hi,

After in depth tests mysql server 5.7 suffered from a bug on install and has been fixed in 2.3RC.
You should try install the 2.3RC and check if your sql problem is still there.

Thanks for your contribution and your report.
Regards,
Gilles Dubois.

**Closed by gillesdubois** 2016-12-23 10:04 UTC
Labels: need approval, question

**Comment by avsavchenko** [comment] 2017-01-12 15:35
same problem

OCS 2.2.1
PHP Version :
7.0.13-0ubuntu0.16.04.1 (apache2handler)
Web Server :
Apache/2.4.18 (Ubuntu)
Database Server :
(Ubuntu) version 5.7.16-0ubuntu0.16.04.1

> Access denied for user 'ocs'@'localhost' (using password: YES)

**Comment by gillesdubois** [comment] 2017-01-12 15:40
Hi @avsavchenko ,

As said in the messages above mysql 5.7 is not compatible with ocsinventory below 2.3.
If you want to have a fully funtionnal server you need to install this version : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.3/OCSNG_UNIX_SERVER-2.3.tar.gz

Regards,
Gilles Dubois.

**Comment by nohnaimer** [comment] 2017-01-13 16:04
On 2.3 works? I test on 2.3RC same error!

**Comment by avsavchenko** [comment] 2017-01-16 08:47
> On 2.3 works? I test on 2.3RC same error!
yea
works only with default password
if I change the password
`#!/bin/bash
### change DB password
echo "Enter new password for mysql database 'ocsweb'."
read MYSQLPASSWORD
echo "Enter root password for mysql."
mysql -h localhost -u root -p mysql -e "SET PASSWORD FOR 'ocs'@'localhost' = PASSWORD('$MYSQLPASSWORD');"
sed -i "s/PSWD_BASE\",\"ocs/PSWD_BASE\",\"$MYSQLPASSWORD/" /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php
sed -i "s/OCS_DB_PWD ocs/OCS_DB_PWD $MYSQLPASSWORD/" /etc/apache2/conf-available/z-ocsinventory-server.conf
service mysql restart
service apache2 restart`

ocsreports webconsole works, but error logs mysql
> Access denied for user 'ocs'@'localhost' (using password: YES)
and inventory server doesn't work (i think), because I do not get reports

**Comment by avsavchenko** [comment] 2017-01-24 13:32
Clear install 2.3 

    PHP Version :
    Web Server :
    Database Server :
    Version OCSReports:

    7.0.13-0ubuntu0.16.04.1 (apache2handler)
    Apache/2.4.18 (Ubuntu)
    (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
    2.3

Everything works, I think the problem is that are created when you install the two accounts 'ocs'@'%' and 'ocs'@'localhost'. Why do we need 'ocs'@'%' ?

```
select user,host from mysql.user;
+------------------+-----------+
| user             | host      |
+------------------+-----------+
| ocs              | %         |
| debian-sys-maint | localhost |
| mysql.sys        | localhost |
| ocs              | localhost |
| root             | localhost |
+------------------+-----------+
```

```
show grants for 'ocs'@'%';
+-------------------------------------------------+
| Grants for ocs@%                                |
+-------------------------------------------------+
| GRANT USAGE ON *.* TO 'ocs'@'%'                 |
| GRANT ALL PRIVILEGES ON `ocsweb`.* TO 'ocs'@'%' |
+-------------------------------------------------+
```

```
show grants for 'ocs'@'localhost';
+---------------------------------------------------------+
| Grants for ocs@localhost                                |
+---------------------------------------------------------+
| GRANT USAGE ON *.* TO 'ocs'@'localhost'                 |
| GRANT ALL PRIVILEGES ON `ocsweb`.* TO 'ocs'@'localhost' |
+---------------------------------------------------------+
```

> tail -10 /var/log/mysql/error.log
> 2017-01-24T13:17:34.059526Z 224 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:17:36.789756Z 227 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:17:38.579866Z 231 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:17:51.027029Z 235 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:17:54.139426Z 244 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:17:57.647647Z 247 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:18:01.801431Z 251 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:18:04.137720Z 254 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:18:08.549969Z 258 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)
> 2017-01-24T13:18:12.942537Z 261 [Note] Access denied for user 'ocs'@'localhost' (using password: YES)

**Comment by gillesdubois** [comment] 2017-01-24 13:43
Hi @avsavchenko,

These users perimeter are created by default on the default install.
Indeed a lot of people doesn't need the ocs@% but we need to be compliant with a wide installation / configuration type.
That's why we keep it :-)
If you got some idea to improve the ocs setup, don't hesitate to create an issue on github. ( Maybe create a select or ask on BD user creation ? )

Thanks for your contribution.

Regards,
Gilles Dubois.

**Comment by nohnaimer** [comment] 2017-02-28 06:35
Not fixed.
Fresh install OCS 2.3 on CentOS 7.3 httpd 2.4.6 php 7.1.2 mysql 5.6.28 (another server)

Same error!
ERROR: MySql connection problem 1045
Access denied for user 'ocsi'@'10.128.217.39' (using password: YES)
ERROR: MySql connection problem 1045
Access denied for user 'ocsi'@'10.128.217.39' (using password: YES)

**Comment by gillesdubois** [comment] 2017-02-28 07:46
Hi @nohnaimer ,

Note : Did you try on the release version or a trunk one ?

I can't help with just that log.
Can you give a step by step on how to reproduce the issue ?
Because on my instalaltion ( Mysql5.6 - Php7 - Ubuntu 16.04 ) if create a new user in the database and then update the needed files ( dbconfig.inc.php, z-ocsinventory-server.confg, ... ) everything is working.
As long as the user can connect to the database it's ok.

Regards,
Gilles Dubois.

**Comment by nohnaimer** [comment] 2017-02-28 08:07
Hi, @gillesdubois 
You can try install Ocs Inventory server on CentOS 7?
My fresh installation:
1. Install Centos 7.3 on server. I set up a network connection, disabled firewalld and SeLinux.
2. yum update -y && reboot
3. Install needed packages on server:
yum install mod_perl make gcc httpd php php-mysql php-gd php-xml php-mbstring php-pclzip perl-Archive-Zip perl-XML-Entities perl-Net-IP perl-Apache-DBI perl-DBD-MySQL perl-XML-Simple php-pecl-zip
4. Download perl-Class-Inspector-1.28-2.el7.noarch.rpm because in repo not this package. Install it.
5. yum install perl-SOAP-Lite
6. Download OCS Server with ocsreports and install
7. Open Installed ocs in browser and take mysql settings. Install. Refresh page and take error.

Maybe problem in VirtualHost, although this is complete nonsense.

I change only:
in httpd.conf
`ServerAdmin`
in ocsinventory-reports.conf
`#Alias /ocsreports /usr/share/ocsinventory-reports/ocsreports

<VirtualHost *:80>

DocumentRoot /usr/share/ocsinventory-reports/ocsreports
ServerName ocs.inside.mts.by

........

</VirtualHost>
`
Change permissions on /usr/share/ocsinventory-reports/ocsreports and /var/lib/ocsinventory-reports on user and group apache

**Comment by BradMK** [comment] 2017-06-15 04:40
This issue is caused by a dollar '$' sign in the MariaDB user password (could also be other characters, so far '*' character works).

**Comment by cPathz** [comment] 2018-02-04 22:40
First of all, excuse me for opening the subject up again.
```
........................
CentOS Linux 7.4.1708
Linux 4.14.14-x86_64-linode94 on x86_64
MySQL version 5.5.56 
..........................
PHP Version : 5.4.16
Web Server : Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3
Database Server : MariaDB Server version 5.5.56-MariaDB
Version OCSReports: 2.4
.........................
```
I have the same problem. OCSInventory only recognizes the default user name and password of the database (user: ocs pass: ocs).
In fact, if I change the password of the user "ocs" the agent stops working and the error appears:
`ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>`

I add users through the console and phpMyAdmin without getting any results. 

Thank you in advance for your cooperation. If you need any further information, please let me know.

\var\log\httpd\error_log
```
[Sun Feb 04 22:30:48.874562 2018] [mpm_prefork:notice] [pid 9244] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3 configured -- resuming normal operations
[Sun Feb 04 22:30:48.874590 2018] [core:notice] [pid 9244] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
DBI connect('database=ocswa;host=localhost;port=3306','ocs',...) failed: Access denied for user 'ocs'@'localhost' (using password: YES) at /usr/local/share/perl5/Apache/Ocsinventory/Server/System.pm line 187.
[Sun Feb 04 22:31:11.239742 2018] [perl:error] [pid 9248] [client 187.162.25.12:12032] Can't call method "do" on an undefined value at /usr/local/share/perl5/Apache/Ocsinventory/Server/System.pm line 189.\n
[Sun Feb 04 22:33:21.871542 2018] [mpm_prefork:notice] [pid 9244] AH00170: caught SIGWINCH, shutting down gracefully
SV = PV(0x564804edec60) at 0x5648049ec518
  REFCNT = 2
  FLAGS = ()
  PV = 0
[Sun Feb 04 22:33:23.162585 2018] [suexec:notice] [pid 9323] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sun Feb 04 22:33:23.408552 2018] [auth_digest:notice] [pid 9323] AH01757: generating secret for digest authentication ...
[Sun Feb 04 22:33:23.409191 2018] [lbmethod_heartbeat:notice] [pid 9323] AH02282: No slotmem from mod_heartmonitor
[Sun Feb 04 22:33:23.437397 2018] [mpm_prefork:notice] [pid 9323] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3 configured -- resuming normal operations
[Sun Feb 04 22:33:23.437422 2018] [core:notice] [pid 9323] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sun Feb 04 22:34:49.282662 2018] [mpm_prefork:notice] [pid 9323] AH00170: caught SIGWINCH, shutting down gracefully
[Sun Feb 04 22:34:50.607194 2018] [suexec:notice] [pid 9359] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sun Feb 04 22:34:50.852774 2018] [auth_digest:notice] [pid 9359] AH01757: generating secret for digest authentication ...
[Sun Feb 04 22:34:50.853428 2018] [lbmethod_heartbeat:notice] [pid 9359] AH02282: No slotmem from mod_heartmonitor
[Sun Feb 04 22:34:50.883095 2018] [mpm_prefork:notice] [pid 9359] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3 configured -- resuming normal operations
[Sun Feb 04 22:34:50.883128 2018] [core:notice] [pid 9359] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

**Comment by mriske** [comment] 2020-07-24 15:59
Hey, same issue here, but also i DONT have an "/etc/httpd/conf.d/z-ocsinventory-server.conf" file and i don't know why.
OCS works fine, but there is this message that the standard password for the database ocsweb is used.
If i change the database password AND the entry in the file "/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php" i get the "ERROR: MySql connection problem 1045" message.

Anyone any idea why i dont have this file?

**Comment by nohnaimer** [comment] 2020-09-28 10:33
Fresh install Percona-server 8.0.21 and ocs inventory 2.8 and same error ERROR: MySql connection problem 1045

@mriske if you install via repo you don't have z-ocsinventory-server.conf you have a ocsinventory-server.conf
