### ISSUE TITLE
[FEATURE] Change code that might cause error in next versions of PHP

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/OCSInventory-ocsreports#831] opened 2019-10-17 15:36 UTC
**Is your feature request related to a problem? Please describe.**
I saw some warning in php log. (currently on php 7.3)

**Describe the solution you'd like**
Fix this warning : 

`[17-Oct-2019 17:33:41 Europe/Paris] PHP Warning:  Use of undefined constant key - assumed 'key' (this will throw an Error in a future version of PHP) `

**Additional context**
Triggered when entering OCS' general configuration menu

**Comment by charleneauger** [comment] 2019-10-17 15:40
Hi @gillesdubois ,

Your issue is a duplicate of #830 . So I close it.

Best regards,
Charlene

**Closed by charleneauger** 2019-10-17 15:40 UTC
Labels: Feature, duplicate, need approval
