### ISSUE TITLE
Error Install Plugins

### ISSUE THREAD

**Issue by meetgyn** [OCSInventory-NG/OCSInventory-ocsreports#850] opened 2019-11-05 14:39 UTC
**You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''','','')' at line 1**

OCSINVENTORY 2.6
OS= DEBIAN 9
MYSQL= mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP= 7.0

**Comment by gillesdubois** [comment] 2019-11-05 14:54
Hi,

We can't guess where the problem is using magic. That why there is a "step to reproduce" in the base template.

You don't follow our issues template thus i'm closing it. 
Please, re-open it using the provided template.

Regards,
Gilles Dubois.

**Closed by gillesdubois** 2019-11-05 14:54 UTC
