### ISSUE TITLE
[BUG] Login over SSL gives "No user provided"; plain HTTP works

### ISSUE THREAD

**Issue by sottolski** [OCSInventory-NG/OCSInventory-ocsreports#1558] opened 2023-09-07 13:39 UTC
**OCS Inventory version**
Version : 2.12.0

**Describe the bug**
When I try to login over https, it fails with "No user provided" error message. However, login over plain http works. What is really strange: After logging in over http, I can switch to https and use the GUI just fine

Any idea how to debug this?

**Comment by Lea9250** [comment] 2023-09-08 13:45
Hi @sottolski ,

Anything in the apache logs of your server while trying to connect ? What is the authentication method ?

Regards,
Léa

**Comment by charleneauger** [comment] 2023-09-26 08:04
Hi @sottolski ,

Any news ?

Best regards,
Charlene

**Comment by sottolski** [comment] 2023-09-26 08:54
Sorry, didn't see the questions. Authentication method is "Local only", with default credentials for user "admin".

Regardings apache logs, strangely only one line is printed after login, with an HTTP 200.

10.20.x.y - - [26/Sep/2023:10:42:17 +0200] "POST / HTTP/1.1" 200 9205 "https://ocs.int.zzz.de/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

Also, nothing obvious in the browsers developer toolbar, all requests are shown with HTTP 200, and the JS console is empty.

The problem is only with HTTPS; after logging in via HTTP, I can switch to HTTPS w/o any problem.

**Comment by charleneauger** [comment] 2023-09-26 09:43
Hi @sottolski ,

Do you have a particular configuration for your `HTTPS` ?

Regards,
Charlene

**Comment by sottolski** [comment] 2023-10-05 08:55
I believe it's pretty standard. Plus, the configuration did work until I upgraded ocs. Anything particular I should look at?

Listen 10.20.127.23:443

NameVirtualHost 10.20.127.23:443

<VirtualHost 10.20.127.23:443>
    ServerName ocs.int.xxx.de
    
    ServerAlias ocs.int.xxx.de
    

    DocumentRoot /usr/share/ocsinventory-reports/ocsreports/

    <Directory /usr/share/ocsinventory-reports/ocsreports/>
        

        AllowOverride all
        order allow,deny
        allow from all
        
        
    </Directory>

    SSLEngine on
    SSLCertificateFile /etc/sslcerts/letsencrypt/tools_int_multi.crt
    SSLCertificateKeyFile /etc/sslcerts/letsencrypt/tools_int_multi.key
    SSLCertificateChainFile /etc/sslcerts/letsencrypt/fullchain.crt
    
    CustomLog /var/log/apache2/access_ocs.int.xxx.de_443.log combined
    ErrorLog /var/log/apache2/error_ocs.int.xxx.de_443.log

    
</VirtualHost>


Alias /ocsreports /usr/share/ocsinventory-reports/ocsreports

<Directory /usr/share/ocsinventory-reports/ocsreports>
    # By default, users can use console from everywhere
      <IfModule mod_authz_core.c>
        # Apache 2.4
        Require all granted
          </IfModule>
          <IfModule !mod_authz_core.c>
        Order deny,allow
        Allow from all
      </IfModule>
    Options Indexes FollowSymLinks
    DirectoryIndex index.php
    AllowOverride Options AuthConfig
    
    # Uncomment following to force use of HTTPS in Administration Server
    #SSLRequireSSL
    
    # PHP tuning (not working on all distribution, use php.ini instead)
    <IfModule mod_php5.c>
        AddType application/x-httpd-php .php
        php_flag file_uploads           on
        # Some PHP tuning for deployment feature up to 8 MB
        # post_max_size must be greater than upload_max_filesize
        # because of HTTP headers 
        php_value post_max_size         101m
        php_value upload_max_filesize   100m
        # You may have to uncomment following on errors
        #php_value max_execution_time -1
        #php_value max_input_time -1
        
        # Uncomment following if you need to specify a mysql socket
        #php_value mysql.default_socket "path/to/mysql/unix/socket"

        #!! Mandatory !! : set magic_quotes_gpc to off (to make ocsreports works correctly)
        php_flag magic_quotes_gpc      off
    </IfModule>
    # Duplicate for php7 compatibility
    <IfModule mod_php7.c>
        AddType application/x-httpd-php .php
        php_flag file_uploads           on
        # Some PHP tuning for deployment feature up to 8 MB
        # post_max_size must be greater than upload_max_filesize
        # because of HTTP headers 
        php_value post_max_size         101m
        php_value upload_max_filesize   100m
        # You may have to uncomment following on errors
        #php_value max_execution_time -1
        #php_value max_input_time -1
        
        # Uncomment following if you need to specify a mysql socket
        #php_value mysql.default_socket "path/to/mysql/unix/socket"

        #!! Mandatory !! : set magic_quotes_gpc to off (to make ocsreports works correctly)
        php_flag magic_quotes_gpc      off
    </IfModule>

    # Uncomment following to allow HTTP body request up to 4 MB
    # instead default 512 KB
    #LimitRequestBody 4194304

</Directory>

################################################################################
# Deployment packages download area
# 
# Alias to put Deployment package files outside Apache document root directory
#
<Directory /var/lib/ocsinventory-reports/download>
   <IfModule mod_authz_core.c>
     # Apache 2.4
     Require all granted
   </IfModule>
   <IfModule !mod_authz_core.c>
     Order deny,allow
     Allow from all
   </IfModule>
</Directory>
Alias /download /var/lib/ocsinventory-reports/download


################################################################################
# Snmp communities area
#
# Alias to put Snmp custom Mibs files outside Apache document root directory
#
<Directory /var/lib/ocsinventory-reports/snmp>
   <IfModule mod_authz_core.c>
     # Apache 2.4
     Require all granted
   </IfModule>
   <IfModule !mod_authz_core.c>
     Order deny,allow
     Allow from all
   </IfModule>
</Directory>
Alias /snmp /var/lib/ocsinventory-reports/snmp

**Comment by gillesdubois** [comment] 2023-12-13 10:21
Hello,

After performing many different test with different configuration and use-cases we cannot reproduce the issue.
We also tried behind a reverse proxy and with a browser with a proxy configured.

It seems there is something wrong with your configuration but its not related to OCS Inventory.
I'll recommend you to double check your installation and if possible to create a sandbox environment to solve the issue.

I'm closing this issue.

Regards,
Gilles DUBOIS.

**Closed by gillesdubois** 2023-12-13 10:21 UTC
Labels: bug, need approval
