### ISSUE TITLE
[BUG] Duplicated entries in function=pack_search&head=1&idchecked=10608&origine=mach

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-ocsreports#1297] opened 2021-11-26 08:09 UTC
**OCS Inventory version**
Version : 2.9.1

**Describe the bug**
When deploying a package on a machine ***from the function=computer screen***, the interface shows duplicated entries

**To Reproduce**
1. Go to an gent (function=computer)
2. Click on deployment in the left menu (function=comput&cat=teledeploy)
3. Click on "Add package" (you land in function=pack_search&origine=mach)
4. Select to use the advanced options of teledeploy or not, it doesn't matter
5. Click validate
6. The list of packages available for deployment shows up and duplicated entries (with empty "PACK_LOCK" field) might be found (See screenshot)

**Expected behavior**
No duplicated entries should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/8179031/143547853-380f3edf-943d-4bc5-a427-034c5ac62378.png)

**Comment by Lea9250** [comment] 2022-01-24 15:04
Hi @StCyr,

I am trying to reproduce this issue. Are these duplicates generated on package activation ? 
I would advise you to delete the entries with empty PACK_LOC fields and see if any other duplicates show up in the future.
Please let me know if this is a recurring problem.

Regards,
Léa

**Comment by charleneauger** [comment] 2022-03-25 16:15
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.

**Closed by charleneauger** 2022-03-25 16:15 UTC
Labels: bug, need approval
